import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import x from "../public/fonts/"
import Navbar from "./components/Navbar";
import localFont from "next/font/local";
import RightSideBar from "./components/RightSideBar";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });
const variableFont = localFont({ src: "../public/fonts/muli-webfont.woff" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={variableFont.className + ""}>
        <Navbar />
        <RightSideBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
